# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8"

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "1024"
    vmware.vmx["numvcpus"] = "1"
  end

  config.vm.define :"centos8-demo" do |node|
    node.vm.hostname = "centos8-demo"
    #node.vm.network "private_network",ip: "192.168.254.15"
  end

end
